name: edu.ws2022.c36.am
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  timelines_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/images/avatars/
    - assets/images/flags/
    - assets/images/news/
    - assets/images/logos/
    - assets/images/medals/
